run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocyclo
linters-settings:
  gocyclo:
    min-complexity: 15
issues:
  exclude-use-default: false
  exclude-rules:
    # Ignore complexity in test files
    - path: _test\.go
      linters:
        - gocyclo
