run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gci
    - gofmt
    - goimports
    - gocritic
    - revive
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - bodyclose
    - exportloopref
    - goconst
    - godot
    - gosec
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - whitespace
  disable:
    - exhaustive
    - exhaustivestruct
    - gocognit
    - gomnd
    - nlreturn
    - wsl
linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - unnamedResult
      - hugeParam
  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters
  gosec:
    excludes:
      - G104 # Audit errors not checked
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/icco/gotak)
issues:
  exclude-use-default: false
  exclude:
    # gosec: Ignore errors in examples and tests
    - 'G104: Errors unhandled\.'
  exclude-rules:
    # Exclude some lints from running on tests files.
    - path: _test\.go
      linters:
        - gosec
        - goconst
        - godot
    # Ignore complexity in test files
    - path: _test\.go
      linters:
        - gocyclo
