language: go
sudo: false
go:
  - "1.15.x"

before_script:
  - go get -u -d -v github.com/fzipp/gocyclo
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  postgresql: 9.6
services:
  - postgresql
install: true
env:
  global:
    - GO111MODULE=on
    - DATABASE_URL="postgres://postgres@localhost/travis_ci_test?sslmode=disable"

script:
  - go test -v -race -cover ./...
  - go vet ./...
  - go run golang.org/x/lint/golint -set_exit_status ./...
  - go run github.com/fzipp/gocyclo/cmd/gocyclo -avg .
