// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://github.com/icco/gotak"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/icco/gotak/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns basic API information and available endpoints",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get API information",
                "responses": {
                    "200": {
                        "description": "HTML page with API information",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/game/new": {
            "get": {
                "description": "Creates a new Tak game with the specified board size",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Create a new game",
                "parameters": [
                    {
                        "description": "Game configuration",
                        "name": "game",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/main.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to game URL",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new Tak game with the specified board size",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Create a new game",
                "parameters": [
                    {
                        "description": "Game configuration",
                        "name": "game",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/main.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to game URL",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/game/{slug}": {
            "get": {
                "description": "Returns the current state of a game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get game state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game slug identifier",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gotak.Game"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/game/{slug}/move": {
            "post": {
                "description": "Submit a move for a specific game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Make a move in a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game slug identifier",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Move details",
                        "name": "move",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.MoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gotak.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/game/{slug}/{turn}": {
            "get": {
                "description": "Returns the state of a game at a specific turn",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get specific turn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game slug identifier",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Turn number",
                        "name": "turn",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gotak.Turn"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns service health status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gotak.Board": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "integer",
                    "format": "int64"
                },
                "squares": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/gotak.Stone"
                        }
                    }
                }
            }
        },
        "gotak.Game": {
            "type": "object",
            "properties": {
                "board": {
                    "$ref": "#/definitions/gotak.Board"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "meta": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gotak.Tag"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "turns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gotak.Turn"
                    }
                }
            }
        },
        "gotak.Move": {
            "type": "object",
            "properties": {
                "moveCount": {
                    "description": "Move only",
                    "type": "integer",
                    "format": "int64"
                },
                "moveDirection": {
                    "type": "string"
                },
                "moveDropCounts": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "square": {
                    "type": "string"
                },
                "stone": {
                    "description": "Both Drop and Move",
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "gotak.Stone": {
            "type": "object",
            "properties": {
                "player": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "gotak.Tag": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "gotak.Turn": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "first": {
                    "$ref": "#/definitions/gotak.Move"
                },
                "number": {
                    "type": "integer",
                    "format": "int64"
                },
                "result": {
                    "type": "string"
                },
                "second": {
                    "$ref": "#/definitions/gotak.Move"
                }
            }
        },
        "main.CreateGameRequest": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "string",
                    "example": "8"
                }
            }
        },
        "main.MoveRequest": {
            "type": "object",
            "properties": {
                "move": {
                    "type": "string",
                    "example": "c3"
                },
                "player": {
                    "type": "integer",
                    "example": 1
                },
                "turn": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GoTak API",
	Description:      "A Tak game server API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
