basePath: /
definitions:
  gotak.Board:
    properties:
      size:
        format: int64
        type: integer
      squares:
        additionalProperties:
          items:
            $ref: '#/definitions/gotak.Stone'
          type: array
        type: object
    type: object
  gotak.Game:
    properties:
      board:
        $ref: '#/definitions/gotak.Board'
      id:
        format: int64
        type: integer
      meta:
        items:
          $ref: '#/definitions/gotak.Tag'
        type: array
      slug:
        type: string
      turns:
        items:
          $ref: '#/definitions/gotak.Turn'
        type: array
    type: object
  gotak.Move:
    properties:
      moveCount:
        description: Move only
        format: int64
        type: integer
      moveDirection:
        type: string
      moveDropCounts:
        items:
          format: int64
          type: integer
        type: array
      square:
        type: string
      stone:
        description: Both Drop and Move
        type: string
      text:
        type: string
    type: object
  gotak.Stone:
    properties:
      player:
        type: integer
      type:
        type: string
    type: object
  gotak.Tag:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  gotak.Turn:
    properties:
      comment:
        type: string
      first:
        $ref: '#/definitions/gotak.Move'
      number:
        format: int64
        type: integer
      result:
        type: string
      second:
        $ref: '#/definitions/gotak.Move'
    type: object
  main.AuthResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/main.User'
    type: object
  main.ConfirmResetRequest:
    properties:
      new_password:
        example: newsecretpassword
        type: string
      token:
        example: reset-token-here
        type: string
    type: object
  main.CreateGameRequest:
    properties:
      size:
        example: "8"
        type: string
    type: object
  main.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: secretpassword
        type: string
    type: object
  main.MoveRequest:
    properties:
      move:
        example: c3
        type: string
      player:
        example: 1
        type: integer
      turn:
        example: 1
        type: integer
    type: object
  main.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: secretpassword
        type: string
    type: object
  main.ResetPasswordRequest:
    properties:
      email:
        example: user@example.com
        type: string
    type: object
  main.UpdateProfileRequest:
    properties:
      name:
        type: string
      preferences:
        type: string
    type: object
  main.User:
    properties:
      avatar_url:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      preferences:
        type: string
      provider:
        type: string
      provider_id:
        type: string
      updated_at:
        type: string
    type: object
host: gotak.app
info:
  contact:
    name: API Support
    url: http://github.com/icco/gotak
  description: A Tak game server API with authentication
  license:
    name: MIT
    url: https://github.com/icco/gotak/blob/main/LICENSE
  title: GoTak API
  version: "1.0"
paths:
  /:
    get:
      consumes:
        - application/json
      description: Returns basic API information and available endpoints
      produces:
        - text/html
      responses:
        "200":
          description: HTML page with API information
          schema:
            type: string
      summary: Get API information
      tags:
        - info
  /auth/confirm-reset:
    post:
      consumes:
        - application/json
      description: Reset password with token
      parameters:
        - description: Confirm reset request
          in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/main.ConfirmResetRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Confirm password reset
      tags:
        - auth
  /auth/login:
    post:
      consumes:
        - application/json
      description: Login with email and password
      parameters:
        - description: User login data
          in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/main.LoginRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.AuthResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
        - auth
  /auth/logout:
    post:
      consumes:
        - application/json
      description: Logout current user (client should discard token)
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout user
      tags:
        - auth
  /auth/profile:
    get:
      consumes:
        - application/json
      description: Get current user profile information
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
        - BearerAuth: []
      summary: Get user profile
      tags:
        - auth
    put:
      consumes:
        - application/json
      description: Update current user profile information
      parameters:
        - description: Profile update data
          in: body
          name: profile
          required: true
          schema:
            $ref: '#/definitions/main.UpdateProfileRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
        - BearerAuth: []
      summary: Update user profile
      tags:
        - auth
  /auth/register:
    post:
      consumes:
        - application/json
      description: Register with email and password
      parameters:
        - description: User registration data
          in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/main.RegisterRequest'
      produces:
        - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.AuthResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
        - auth
  /auth/reset-password:
    post:
      consumes:
        - application/json
      description: Send password reset token for email
      parameters:
        - description: Reset password request
          in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/main.ResetPasswordRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Request password reset
      tags:
        - auth
  /game/{slug}:
    get:
      consumes:
        - application/json
      description: Returns the current state of a game
      parameters:
        - description: Game slug identifier
          in: path
          name: slug
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gotak.Game'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get game state
      tags:
        - game
  /game/{slug}/{turn}:
    get:
      consumes:
        - application/json
      description: Returns the state of a game at a specific turn
      parameters:
        - description: Game slug identifier
          in: path
          name: slug
          required: true
          type: string
        - description: Turn number
          in: path
          name: turn
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gotak.Turn'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get specific turn
      tags:
        - game
  /game/{slug}/move:
    post:
      consumes:
        - application/json
      description: Submit a move for a specific game
      parameters:
        - description: Game slug identifier
          in: path
          name: slug
          required: true
          type: string
        - description: Move details
          in: body
          name: move
          required: true
          schema:
            $ref: '#/definitions/main.MoveRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gotak.Game'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Make a move in a game
      tags:
        - game
  /game/new:
    get:
      consumes:
        - application/json
      description: Creates a new Tak game with the specified board size
      parameters:
        - description: Game configuration
          in: body
          name: game
          schema:
            $ref: '#/definitions/main.CreateGameRequest'
      produces:
        - application/json
      responses:
        "307":
          description: Redirect to game URL
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new game
      tags:
        - game
    post:
      consumes:
        - application/json
      description: Creates a new Tak game with the specified board size
      parameters:
        - description: Game configuration
          in: body
          name: game
          schema:
            $ref: '#/definitions/main.CreateGameRequest'
      produces:
        - application/json
      responses:
        "307":
          description: Redirect to game URL
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new game
      tags:
        - game
  /healthz:
    get:
      consumes:
        - application/json
      description: Returns service health status
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
        - health
securityDefinitions:
  BearerAuth:
    description: 'JWT token in format: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
